#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/bobbydodd.h"
#include "images/georgiatech.h"
#include "images/player.h"
#include "images/win.h"
#include "images/uga.h"
#include "images/ugaplayer.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  INFO,
  PLAY,
  WIN,
  LOSE,
};

Player p;

int main(void) {
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  drawFullScreenImageDMA(bobbydodd);

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
      drawFullScreenImageDMA(bobbydodd);
      state = START;
    }

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        waitForVBlank();
        drawString(20, 80, "Beat the DAWGS !!!!", WHITE);
        drawString(40, 80, "Press ENTER to Start", YELLOW);
        if (KEY_DOWN(BUTTON_START, currentButtons)) {
          fillScreenDMA(WHITE);
          state = INFO;
        }
        break;
      case INFO:
        waitForVBlank();
        drawString(20, 20, "It's 4th Quarter and GT is down 1.", BLACK);
        drawString(40, 20, "Run the ball to the endzone, and", BLACK);
        drawString(60, 20, "send uGA back to Athens!!!", BLACK);
        drawString(100, 20, "Press x to start playing", BLACK);
        if (KEY_DOWN(BUTTON_A, currentButtons)) {
          state = PLAY;
        }
        break;
      case PLAY:
        waitForVBlank();
        drawImageDMA(0, 0, 240, 160, georgiatech);
        int won = playFootball();
        if (won == 0) {    
          drawFullScreenImageDMA(bobbydodd);
          state = START;
        } else if (won == 1) {
          drawFullScreenImageDMA(win);
          state = WIN;
        } else {
          drawFullScreenImageDMA(uga);
          state = LOSE;
        }
        break;
      case WIN:
        drawString(40, 20, "You won! Press x to play again.", WHITE);
        if (KEY_DOWN(BUTTON_A, currentButtons)) {
          drawFullScreenImageDMA(bobbydodd);
          state = START;
        }
        break;
      case LOSE:
        drawString(110, 10, "OH NO, uGA won! Press x to try again.", WHITE);
        if (KEY_DOWN(BUTTON_A, currentButtons)) {
          drawFullScreenImageDMA(bobbydodd);
          state = START;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }



  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}

Player createPlayer(void) {
  Player p;
  p.pos.row = 80;
  p.pos.col = 42;
  drawImageDMA(80, 42, 8, 12, player);
  return p;
}

Defender createDefender(int defNumber) {
  Defender d;
  d.pos.row = 40 * defNumber;
  d.pos.col = 40 * (defNumber) + 100;
  drawImageDMA(d.pos.row, d.pos.col, 8, 12, ugaplayer);
  return d;
}

void moveDefender(Defender *d) {
    if (d->pos.row > p.pos.row) {
    // undrawImageDMA(d->pos.row, d->pos.col, 8, 12, georgiatech);
    d->pos.row--;
    drawImageDMA(d->pos.row, d->pos.col, 8, 12, ugaplayer);
    undrawImageDMA(d->pos.row + 12, d->pos.col, 8, 12, georgiatech);
  } else if (d->pos.row < p.pos.row) {
    // undrawImageDMA(d->pos.row, d->pos.col, 8, 12, georgiatech);
    d->pos.row++;
    drawImageDMA(d->pos.row, d->pos.col, 8, 12, ugaplayer);
    undrawImageDMA(d->pos.row - 12, d->pos.col, 8, 12, georgiatech);
  } else if (d->pos.col < p.pos.col) {
    // undrawImageDMA(d->pos.row, d->pos.col, 8, 12, georgiatech);
    d->pos.col++;
    drawImageDMA(d->pos.row, d->pos.col, 8, 12, ugaplayer);
    undrawImageDMA(d->pos.row, d->pos.col - 8, 8, 12, georgiatech);
  } else if (d->pos.col > p.pos.col) {
    // undrawImageDMA(d->pos.row, d->pos.col, 8, 12, georgiatech);
    d->pos.col--;
    drawImageDMA(d->pos.row, d->pos.col, 8, 12, ugaplayer);
    undrawImageDMA(d->pos.row, d->pos.col + 8, 8, 12, georgiatech);
  }
  
}

int yardsToGo(Player p) {
  return (210 - p.pos.col) / 1.82;
}

void printYardsToGo(int yards) {
  int ytg = yards;
  char infoString[16];
  if (ytg < 10) {
    sprintf(infoString, "0%d yards to go!", ytg);
  } else {
    sprintf(infoString, "%d yards to go!", ytg);
  }
  if (ytg > 0) {
    drawString(150, 80, infoString, BLACK);
  }
}

void movePlayer(u32 buttons) {
  if (KEY_DOWN(BUTTON_UP, buttons)) {
    p.pos.row--;
    if (p.pos.row < 0) {
        p.pos.row = 0;
    }
      waitForVBlank();
      drawImageDMA(p.pos.row, p.pos.col, 8, 12, player);
      undrawImageDMA(p.pos.row + 12, p.pos.col, 8, 12, georgiatech);
    } if (KEY_DOWN(BUTTON_DOWN, buttons)) {
      p.pos.row++;
      if (p.pos.row > 120) {
        p.pos.row = 120;
      }
      waitForVBlank();
      drawImageDMA(p.pos.row, p.pos.col, 8, 12, player);
      undrawImageDMA(p.pos.row - 12, p.pos.col, 8, 12, georgiatech);
    } if (KEY_DOWN(BUTTON_RIGHT, buttons)) {
      p.pos.col++;
      if (p.pos.col > 220) {
        p.pos.col = 220;
      }
      waitForVBlank();
      drawImageDMA(p.pos.row, p.pos.col, 8, 12, player);
      undrawImageDMA(p.pos.row, p.pos.col - 8, 8, 12, georgiatech);
    } if (KEY_DOWN(BUTTON_LEFT, buttons)) {
      p.pos.col--;
      if (p.pos.col < 20) {
        p.pos.col = 20;
      }
      waitForVBlank();
      drawImageDMA(p.pos.row, p.pos.col, 8, 12, player);
      undrawImageDMA(p.pos.row, p.pos.col + 8, 8, 12, georgiatech);
    }
} 

int playFootball(void) {
  Defender d1 = createDefender(1);
  d1.pos.row++;
  p = createPlayer();
  u32 buttons;
  int oldYardsToGo = 150;
  int counter = 0;
  while (1) {
    buttons = BUTTONS;
    if (KEY_DOWN(BUTTON_SELECT, buttons)) {    
      return 0;
    } else if (p.pos.col >= 210) {
      return 1;
    } else if (abs(p.pos.col - d1.pos.col) < 8 && abs(p.pos.row - d1.pos.row) < 10) {
      return 2;
    }
    if (counter % 3 == 0) {
      moveDefender(&d1);
    }
    movePlayer(buttons);
    int yards = yardsToGo(p);
    if (abs(yards - oldYardsToGo) > 0.49) {
      undrawImageDMA(150, 80, 15, 40, georgiatech);
      printYardsToGo(yards);
      oldYardsToGo = yards;
    }
    drawString(5, 10, "4TH QTR   0:00", BLACK);
    drawString(5, 135, "GT: 23  UGA: 24", BLACK);
    
    counter++;
  }
}
